version: "3"

services:
  server:
    build: ./server
    container_name: myapp2-server
    ports:
      - "3000:3000"
    restart: always

  client:
    build: ./client
    container_name: myapp2-client
    ports:
      - "80:80"
    restart: always
